# Generated by Django 4.2.3 on 2023-07-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_collection_coll_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_cover',
            field=models.ImageField(upload_to='collection_covers/'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='piececover',
            field=models.ImageField(upload_to='piece_covers/'),
        ),
    ]
