# Generated by Django 4.2.3 on 2023-07-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_collection_coll_cover_alter_piece_piececover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_cover',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='piece',
            name='piececover',
            field=models.CharField(max_length=1000),
        ),
    ]
