# Generated by Django 4.2.3 on 2023-07-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_collection_coll_cover_alter_piece_piececover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
    ]
