# Generated by Django 4.2.3 on 2023-07-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='coll_buy',
            field=models.CharField(default='default value', max_length=5000),
        ),
    ]
