# Generated by Django 4.2.3 on 2023-07-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_piece_coll_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page', models.CharField(max_length=2000)),
                ('home_cover', models.CharField(max_length=1000)),
            ],
        ),
    ]
