# Generated by Django 4.2.3 on 2023-07-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_home_home_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.CharField(default='home', max_length=200),
        ),
    ]
